# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.version)
np.show_config()

<module 'numpy.version' from 'C:\\Users\\ahmad\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy\\version.py'>
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_inf

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
null_vec = np.zeros(10)
null_vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
null_vec.size * null_vec.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
null_vec = np.zeros(10)
null_vec[4] = 1
null_vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
range_vec = np.arange(10, 50)
range_vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
range_vec[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
range_matrix = np.arange(0, 9).reshape((3, 3))
range_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
np.random.random((3, 3, 3))

array([[[0.61191169, 0.96719579, 0.23235761],
        [0.74314426, 0.99862333, 0.67779839],
        [0.42431875, 0.62922747, 0.97482788]],

       [[0.09899729, 0.28219867, 0.27868577],
        [0.53615003, 0.89796703, 0.06670733],
        [0.35156884, 0.65070656, 0.92874901]],

       [[0.82073158, 0.53928735, 0.06810779],
        [0.91750343, 0.35693385, 0.85994416],
        [0.21350976, 0.05426876, 0.22402443]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
rand_arr = np.random.random((10, 10))
print(rand_arr.min())
print(rand_arr.max())

0.012755028169694205
0.9820083630062979


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
np.mean(np.random.random(30))

0.46167202577802957

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((13, 13))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
arr = np.ones((13, 13))
arr = np.pad(arr, pad_width=1, mode="constant", constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan

False

False

np.nan

True

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
arr = np.ones((5, 5))
arr = np.diag(1 + np.arange(4), k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
arr = np.ones((8, 8))
arr[1::2, ::2] = 0
arr[::2, 1::2] = 0
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
A = [[0, 1],
     [1, 0]]
np.tile(A, (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
arr = np.random.random((5, 5))
arr = (arr - np.mean(arr)) / np.std(arr)
arr

array([[-0.14984643, -0.67481021, -1.22729745,  1.28935986,  0.58991251],
       [ 0.16828629, -1.46238674, -0.36017002,  1.42848916,  1.57845639],
       [-0.345552  , -0.00712678, -0.37948347,  0.93144449,  1.2355255 ],
       [-1.23287783, -1.10615036, -0.86466666, -1.45384864,  0.71827168],
       [ 1.34091075,  1.59945209, -0.82639465, -0.2406263 , -0.5488712 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [22]:
rgba = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
rgba

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
arr = np.arange(13)
arr[(3 < arr) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

All but the last

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\ahmad\AppData\Local\Temp\ipykernel_3336\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\ahmad\AppData\Local\Temp\ipykernel_3336\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [26]:
arr = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(arr)), arr)

array([ 3., -6., -2., -8.,  7.,  4.,  5., -6., 10., -3.])

#### 30. How to find common values between two arrays? (★☆☆)

[intersect1d()](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

In [27]:
arr1 = np.arange(10, 29)
arr2 = np.arange(3, 28)
np.intersect1d(arr1, arr2)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [28]:
# np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\ahmad\AppData\Local\Temp\ipykernel_3336\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [30]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [31]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [32]:
A = np.ones(13) 
B = np.ones(13) * 2
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A, 2, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5, -1.5, -1.5, -1.5, -1.5, -1.5, -1.5, -1.5, -1.5,
       -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [33]:
arr = np.random.uniform(0,10,10)
print(np.floor(arr))
print(np.trunc(arr))
print(arr // 1)
print(arr.astype(int))

[2. 4. 9. 1. 9. 3. 6. 2. 7. 1.]
[2. 4. 9. 1. 9. 3. 6. 2. 7. 1.]
[2. 4. 9. 1. 9. 3. 6. 2. 7. 1.]
[2 4 9 1 9 3 6 2 7 1]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [35]:
def generate():
    for i in range(10):
        yield i
np.fromiter(generate(), dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [36]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [37]:
np.sort(np.random.random(10))

array([0.07192323, 0.12912485, 0.19633609, 0.30376184, 0.33774402,
       0.42352771, 0.57753091, 0.69882003, 0.70847036, 0.90236645])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [38]:
arr = np.arange(13)
np.add.reduce(arr)

78

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [39]:
A = np.random.randint((29, 10, 2))
B = np.random.randint((29, 10, 2))
# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(np.allclose(A, B))

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
print(np.array_equal(A, B))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
arr = np.arange(13)
arr.flags.writeable = False
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [41]:
arr = np.random.random((10,2))
X,Y = arr[:,0], arr[:,1]
R = np.sqrt(X**2 + Y**2)
tan = np.arctan2(Y, X)
print(R)
print(tan)

[0.1790823  0.60987361 0.35771606 0.39599913 0.54805548 0.56281959
 0.77826903 0.84705327 1.05594679 0.94819431]
[0.5822135  1.39884487 1.20258347 0.099327   0.32825189 1.30717053
 0.15402602 1.53542403 0.73961779 0.18369574]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [42]:
arr = np.random.random(10)
print(arr)
arr[arr.argmax()] = 0
arr

[0.65454376 0.39991469 0.71978804 0.51238577 0.85994308 0.93152556
 0.54374011 0.49878724 0.51230817 0.05052974]


array([0.65454376, 0.39991469, 0.71978804, 0.51238577, 0.85994308,
       0.        , 0.54374011, 0.49878724, 0.51230817, 0.05052974])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [43]:
dtype = [('x', float), ('y', float)]
arr = np.zeros((5, 5), dtype=dtype)
arr['x'], arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
arr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [44]:
X = np.arange(13)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [45]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [46]:
arr = np.zeros((28, 29))
print(arr) # Or simply just the name of the array 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [47]:
arr = np.arange(100)
vec = np.random.uniform(0, 100)
i = np.abs(arr - vec).argmin()
print(arr)
print(vec)
arr[i]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
96.5312655608003


97

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [48]:
dtype = [('position', [('x', float), ('y', float)]), ('color', [('r', int), ('g', int), ('b', int)])]
arr = np.ones(3, dtype=dtype)
arr

array([((1., 1.), (1, 1, 1)), ((1., 1.), (1, 1, 1)),
       ((1., 1.), (1, 1, 1))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<i4'), ('g', '<i4'), ('b', '<i4')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [49]:
arr = np.random.random((100, 2))
X, Y = np.atleast_2d(arr[:,0], arr[:,1])
np.sqrt( (X - X.T)**2 + (Y - Y.T)**2)

array([[0.        , 0.48312238, 0.16742893, ..., 0.32681422, 0.25768455,
        0.51354763],
       [0.48312238, 0.        , 0.46647335, ..., 0.2807822 , 0.44562749,
        0.89705653],
       [0.16742893, 0.46647335, 0.        , ..., 0.41158828, 0.40101348,
        0.43675374],
       ...,
       [0.32681422, 0.2807822 , 0.41158828, ..., 0.        , 0.17372209,
        0.83100349],
       [0.25768455, 0.44562749, 0.40101348, ..., 0.17372209, 0.        ,
        0.76588511],
       [0.51354763, 0.89705653, 0.43675374, ..., 0.83100349, 0.76588511,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [50]:
arr = (np.random.random(13) * 10).astype(np.float32)
int_arr = arr.view(np.int32)
int_arr[:] = arr
int_arr

array([8, 0, 6, 3, 9, 1, 5, 2, 2, 6, 3, 3, 2])

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [51]:
from io import StringIO
s = StringIO("1, 2, 3, 4, 5 6,  ,  , 7, 8 ,  , 9, 10, 11")
np.genfromtxt(s, dtype=int, delimiter=",")

array([ 1,  2,  3,  4, -1, -1, -1,  7,  8, -1,  9, 10, 11])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [52]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [53]:
X, Y = np.meshgrid(np.linspace(-1,1,13), np.linspace(-1,1,13))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

array([[0.36787944, 0.42860385, 0.48567179, 0.53526143, 0.57375342,
        0.59816485, 0.60653066, 0.59816485, 0.57375342, 0.53526143,
        0.48567179, 0.42860385, 0.36787944],
       [0.42860385, 0.49935179, 0.56583971, 0.62361492, 0.66846063,
        0.69690156, 0.70664828, 0.69690156, 0.66846063, 0.62361492,
        0.56583971, 0.49935179, 0.42860385],
       [0.48567179, 0.56583971, 0.64118039, 0.70664828, 0.75746513,
        0.78969293, 0.8007374 , 0.78969293, 0.75746513, 0.70664828,
        0.64118039, 0.56583971, 0.48567179],
       [0.53526143, 0.62361492, 0.70664828, 0.77880078, 0.8348063 ,
        0.87032473, 0.8824969 , 0.87032473, 0.8348063 , 0.77880078,
        0.70664828, 0.62361492, 0.53526143],
       [0.57375342, 0.66846063, 0.75746513, 0.8348063 , 0.89483932,
        0.93291196, 0.94595947, 0.93291196, 0.89483932, 0.8348063 ,
        0.75746513, 0.66846063, 0.57375342],
       [0.59816485, 0.69690156, 0.78969293, 0.87032473, 0.93291196,
        0.97260448, 0.98620

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [54]:
arr = np.zeros((28, 10))
p = 13
np.put(arr, np.random.choice(range(28*10), p, replace=False), 1)
arr

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [55]:
X = np.random.rand(28, 10)
X - X.mean(axis=1, keepdims=True)

array([[ 0.16338455,  0.59475   ,  0.06244472, -0.26736979,  0.0018657 ,
        -0.34754115, -0.26039411, -0.21225582,  0.39521771, -0.13010182],
       [ 0.29325766, -0.44785748,  0.3311399 , -0.27350144, -0.02764386,
        -0.45315408,  0.05318734, -0.11654586,  0.22642674,  0.41469108],
       [-0.54891642,  0.44322482, -0.23110601,  0.37723895,  0.26692035,
        -0.09621346, -0.24005663, -0.00230654, -0.38019089,  0.41140584],
       [-0.3934091 , -0.02825579,  0.16786712,  0.46320568, -0.05355755,
         0.00638978,  0.46084182, -0.31468423,  0.08167935, -0.39007708],
       [ 0.29962226,  0.07509119,  0.03130538,  0.28244726, -0.15541208,
         0.2135738 , -0.61606409,  0.12612774, -0.54888892,  0.29219744],
       [-0.37810311,  0.0473989 , -0.13104529,  0.20352136, -0.2135393 ,
         0.04854217,  0.15145464, -0.38896287,  0.2916595 ,  0.36907399],
       [-0.50952083,  0.46390677, -0.07776688,  0.24302125, -0.26781312,
         0.18060173,  0.12566068,  0.20717997

#### 59. How to sort an array by the nth column? (★★☆)

In [56]:
arr = np.random.randint(0, 10, (3, 3))
print(arr)
arr[arr[:, 1].argsort()]

[[0 2 5]
 [7 3 5]
 [7 4 5]]


array([[0, 2, 5],
       [7, 3, 5],
       [7, 4, 5]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [57]:
arr = np.random.randint(0, 10, (3, 3))
~arr.any(axis=0).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [58]:
arr = np.random.uniform(0, 1, 10)
v = 0.7
arr.flat[np.abs(arr - v).argmin()]

0.7749735465976775

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [59]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x, y, z in np.nditer([A, B, None]):
    z[...] = x + y
it.operands[2]

array([[1, 0, 8],
       [3, 0, 0],
       [2, 5, 1]])

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [60]:
arr1 = np.ones(13)
arr2 = np.random.randint(0, len(arr), 13)
print(arr2)
np.add.at(arr1, arr2, 1)
arr1

[9 5 1 4 3 7 1 8 7 5 1 3 2]


array([1., 4., 2., 3., 2., 3., 1., 3., 2., 2., 1., 1., 1.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [61]:
X = [1, 2, 3, 4, 5, 6]
I = [2, 1, 3, 0, 5, 4]
np.bincount(I, X)

array([4., 2., 1., 3., 6., 5.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [62]:
arr = np.random.randint(0, 4, (256, 256, 3)).astype(np.ubyte)
len(np.unique(arr.reshape(-1, 3), axis=0))

64

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [63]:
arr = np.random.randint(0, 13, (2, 3, 4, 5))
arr.sum(axis=(-2, -1))

array([[106, 120, 122],
       [101, 109, 112]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [64]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_sums / D_counts

array([0.51952531, 0.33565435, 0.53733608, 0.44802798, 0.58018216,
       0.45020167, 0.40873451, 0.57987153, 0.56796166, 0.51372208])

#### 69. How to get the diagonal of a dot product? (★★★)

In [65]:
A = np.random.uniform(0,1, (7, 7))
B = np.random.uniform(0,1, (7, 7))
np.sum(A + B.T, axis=1)

array([8.90195503, 5.41475052, 6.23161507, 5.92808489, 6.53272314,
       6.56538714, 6.78884896])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [66]:
arr = np.array([1, 2, 3, 4, 5])
n = 3
arr_zeros = np.zeros(len(arr) + len(arr - 1) * n)
arr_zeros[::n+1] = arr
arr_zeros

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.,
       0., 0., 0.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [67]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5 , 5))
A * B[:, :, np.newaxis]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [123]:
arr = np.ones((5 , 5))
arr[1] = 28
arr[3] = 29
print(arr)
arr[[1, 3]] = arr[[3, 1]]
arr

[[ 1.  1.  1.  1.  1.]
 [28. 28. 28. 28. 28.]
 [ 1.  1.  1.  1.  1.]
 [29. 29. 29. 29. 29.]
 [ 1.  1.  1.  1.  1.]]


array([[ 1.,  1.,  1.,  1.,  1.],
       [29., 29., 29., 29., 29.],
       [ 1.,  1.,  1.,  1.,  1.],
       [28., 28., 28., 28., 28.],
       [ 1.,  1.,  1.,  1.,  1.]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

[( 1, 10) ( 1, 68) (10, 68) (14, 38) (14, 54) (16, 25) (16, 44) (25, 44)
 (33, 39) (33, 47) (33, 71) (33, 90) (38, 45) (38, 54) (38, 95) (39, 90)
 (42, 71) (42, 94) (43, 65) (43, 75) (44, 64) (44, 75) (45, 95) (47, 71)
 (64, 75) (65, 75) (68, 82) (68, 96) (71, 94) (82, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [85]:
C = np.bincount([1, 2, 2, 3, 4, 5, 6, 7, 7])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 2, 2, 3, 4, 5, 6, 7, 7])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [86]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

moving_average(np.arange(13), 7)

array([3., 4., 5., 6., 7., 8., 9.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [89]:
Z = np.random.uniform(-1.0,1.0,13)
print(Z)
np.negative(Z)

[ 0.80786134  0.18471349 -0.92735141  0.98649711 -0.6540708  -0.60301468
  0.36315971 -0.06709972 -0.05983352 -0.4355254  -0.64270973  0.31109059
 -0.63055401]


array([-0.80786134, -0.18471349,  0.92735141, -0.98649711,  0.6540708 ,
        0.60301468, -0.36315971,  0.06709972,  0.05983352,  0.4355254 ,
        0.64270973, -0.31109059,  0.63055401])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)